export type VodDetails = {
  id: number;
  status: string;
  ai_text_status: string;
  url: string;
  key: string;
  title: string;
  description: string;
  is_encrypted: boolean;
  start_time: number;
  hidden: boolean;
  tag: string;
  resolution: string;
  pg_state: number;
  duration: number;
  storage: number;
  transcode_vod_id: number;
  language: string;
  user: number;
  category: number[];
};
